name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Build frontend
        run: |
          cd client
          npm install
          npm run build

      - name: Build backend
        run: |
          cd ../server
          npm install
          npm run build
          cp: -R ../client/dist .

      - name: Zip backend
        run: zip -r backend.zip .

      - name: Install AWS Elastic Beanstalk CLI
        run: pip install awsebcli

      - name: Deploy application to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v15
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: 'Grocery-app'
          environment_name: 'Grocery-app-env'
          version_label: 'deploy-${{ github.run_number }}'
          region: 'eu-north-1b'
          deployment_package: 'backend.zip'

      - name: Deploy to AWS Elastic Beanstalk
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-north-1b'
        run: |
          eb init -p Node.js your-app-name --region $AWS_REGION
          eb deploy Grocery-app-env -l "deploy-${{ github.run_number }}"
